### ISSUE TITLE
发生错误了： name 'pyfiglet' is not defined

### ISSUE THREAD

**Issue by fmwww** [vanpersiexp/chongding#5]
发生错误了： name 'pyfiglet' is not defined
这个模块我安装了，还是报这个错误

**Comment by vanpersiexp** [comment]
@FMWWW 使用用pip3安装的么

**Comment by fmwww** [comment]
pip...但是我再执行pip3 install pyfiglet，提示已经安装了

**Comment by fmwww** [comment]
搞定了，可能是执行`pip3 install -r related.txt`没加`sudo`，现在可以了
